### ISSUE TITLE
How to Enhance Sub-Menu Styles in WordPress Using Custom CSS

### ISSUE THREAD

**Issue by ds4cabs** [ds4cabs/CABS_Smart_Website#23]
Styling sub-menus in WordPress typically involves adding custom CSS to target the specific classes or IDs associated with those menu elements. Here’s a step-by-step guide on how to find these selectors and customize them:

### 1. **Identify CSS Selectors**
   First, you need to identify the CSS selectors used by your theme for the sub-menus. You can do this using the browser's developer tools (Right-click on the sub-menu and select "Inspect" in Chrome or Firefox).

### 2. **Access Custom CSS Section**
   - **WordPress Customizer:** Go to your WordPress dashboard, navigate to **Appearance > Customize**. Here, look for 'Additional CSS' or a similar section.
   - **CSS Plugin:** If your theme does not support direct CSS editing, you can use a plugin like "Simple Custom CSS" to add your styles.

### 3. **Add Custom CSS**
   Here are a few examples of CSS properties you might consider changing:

   - **Font Size:** Adjust the size of the text in the sub-menus.
   - **Color:** Change the text color for better visibility or matching your site’s theme.
   - **Background:** Set a different background for the sub-menus to distinguish them from the main menu.
   - **Padding and Margin:** Adjust spacing inside and around each submenu item to improve layout and readability.

### Example CSS Code:
Here’s some example CSS that you might use. You’ll need to replace `.sub-menu` with the actual selector you find for your theme:

```css
/* Style for sub-menu items */
.nav-menu .sub-menu {
    background-color: #f9f9f9;  /* Light grey background */
    color: #333333;             /* Dark grey text */
    font-size: 14px;            /* Smaller font size */
}

.nav-menu .sub-menu a {
    color: #0066cc;             /* Blue text for links */
    padding: 10px 15px;         /* Padding around the text */
}

.nav-menu .sub-menu a:hover {
    background-color: #0044cc;  /* Darker background on hover */
    color: #ffffff;             /* White text on hover */
}
```

### 4. **Test Your Changes**
   After applying the CSS, visit your site to see the changes in action. It’s a good practice to check how these changes look on different devices and browsers to ensure consistency.

### 5. **Iterate**
   Depending on your theme and specific needs, you may need to go back and tweak the CSS a bit more. Use the inspect tool as needed to make adjustments.

This process will help you achieve a more visually appealing sub-menu that matches the overall style of your website. If you encounter any issues or need more specific guidance, let me know!
